create_training_data:
  base_sft:
    prompt_template_file: prompts/alfworld/alfworld_template.j2
    logs_dir: data/ablation_privileged_sft/alfworld/privileged_demonstrations
    data_dir: data/ablation_privileged_sft/alfworld/sft/iter0
    train_split: 0.85
    input_fields:
      observation: observation
      candidate_actions: candidate_actions
      reason: reason
      action: action
      task: task
    output_fields:
      reason: reason
      action: action
  sft:
    prompt_template_file: prompts/alfworld/alfworld_template.j2
    logs_dir: data/alfworld/corrections/iter{prev_iter}/correction
    data_dir: data/alfworld/sft/iter{iter}
    train_split: 0.85
    input_fields:
      observation: original_observation
      candidate_actions: candidate_actions
      reason: original_reason
      action: original_action
      task: task
    output_fields:
      reason: corrected_reason
      action: corrected_action
  pref:
    prompt_template_file: prompts/alfworld/alfworld_template.j2
    logs_dir: data/alfworld/corrections/iter{prev_iter}/correction
    data_dir: data/alfworld/pref/iter{iter}
    train_split: 0.85
    input_fields:
      observation: original_observation
      candidate_actions: candidate_actions
      reason: original_reason
      action: original_action
      task: task
    output_fields:
      chosen_reason: corrected_reason
      chosen_action: corrected_action
      rejected_reason: original_reason
      rejected_action: original_action
collect_privileged_sft_demonstrations:
  verbose: true
  debug: false
  logdir: data/ablation_privileged_sft/alfworld/privileged_demonstrations
  exact_path: true
  start_env_idx: 3000
  max_env_idxs: null
  eval_set: train
  privileged_state_file: data/alfworld/privileged_state.json
  agents:
    - type: openai
      model_id: gpt-4o
      prompt_template_file: prompts/alfworld/alfworld_privileged_agent_template.j2
upload_models_to_hf:
  model_id_path: save/240912/alfworld_sft/iter2/checkpoint-907
  new_model_name: Meta-Llama-3-8B-Instruct-sft-alfworld-iter2
  organization_name: leap-llm