upload_models_to_hf:
  model_id_path: save/241117/alfworld_webshop_intercode_sft/iter0/checkpoint-14639/
  new_model_name: Meta-Llama-3-8B-Instruct-sft-alfworld-webshop-intercode-iter0
  organization_name: leap-llm