env_type: bash
env_image_name: intercode-nl2bash
env_data_path: env_assets/intercode/data/nl2bash/nl2bash_fs.json
env_verbose: false
env_preprocess: null
verbose: 1
debug: false
logdir: data/eval/intercode_bash
exact_path: false
eval_set: test
start_env_idx: null
max_env_idxs: null
max_actions: 10
agents:
  - type: openai
    model_id: gpt-4o
    prompt_template_file: prompts/intercode_bash/intercode_bash_template.j2
  - type: openai
    model_id: gpt-4o-mini
    prompt_template_file: prompts/intercode_bash/intercode_bash_template.j2
  - type: sglang_server
    model_id: leap-llm/Meta-Llama-3.1-70B-Instruct-sft-intercode-bash-iter0
    server_url: http://localhost:30000/
    prompt_template_file: prompts/intercode_bash/intercode_bash_template.j2
  - type: sglang_server
    model_id: leap-llm/Meta-Llama-3.1-70B-Instruct-sft-intercode-bash-iter1
    server_url: http://localhost:30000/
    prompt_template_file: prompts/intercode_bash/intercode_bash_template.j2
  # - type: hf_space
  #   model_id: leap-llm/Meta-Llama-3.1-8B-Instruct-sft-intercode-bash-iter1
  #   space_id: sc2582/leap_llm_space2
  #   prompt_template_file: prompts/intercode_bash/intercode_bash_template.j2