collect_logs_webshop:
  training_logs_filepath: data/webshop/raw/il_trajs_finalized_images.jsonl
  log_dir: data/webshop/raw/raw_logs
annotate_reason:
  prompt_template_file: prompts/webshop/reasoning_template.j2
  log_dir: data/webshop/raw/raw_logs/
  output_log_dir: data/webshop/raw/raw_logs_w_reason_new/
extract_privileged_state_webshop:
  privleged_state_filename: data/webshop/privileged_state.json
create_training_data:
  base_sft:
    prompt_template_file: prompts/webshop/webshop_template.j2
    logs_dir: data/webshop/raw/raw_logs_w_reason
    data_dir: data/webshop/sft/iter0
    train_split: 0.85
    input_fields:
      observation: observation
      candidate_actions: candidate_actions
      reason: reason
      action: action
    output_fields:
      reason: reason
      action: action
  sft:
    prompt_template_file: prompts/webshop/webshop_template.j2
    logs_dir: data/webshop/corrections/iter{prev_iter}/correction
    data_dir: data/webshop/sft/iter{iter}
    train_split: 0.85
    input_fields:
      observation: original_observation
      candidate_actions: candidate_actions
      reason: original_reason
      action: original_action
    output_fields:
      reason: corrected_reason
      action: corrected_action
  pref:
    prompt_template_file: prompts/webshop/webshop_template.j2
    logs_dir: data/webshop/corrections/iter{prev_iter}/correction
    data_dir: data/webshop/pref/iter{iter}
    train_split: 0.85
    input_fields:
      observation: original_observation
      candidate_actions: candidate_actions
      reason: original_reason
      action: original_action
    output_fields:
      chosen_reason: corrected_reason
      chosen_action: corrected_action
      rejected_reason: original_reason
      rejected_action: original_action
rollout_student_trajectory:
  verbose: false
  debug: false
  logdir: data/webshop/corrections/iter{iter}/rollout
  exact_path: true
  eval_set: train
  start_env_idx: null
  max_env_idxs: null
  max_actions: 15
  agents:
    - type: hf
      model_id: leap-llm/Meta-Llama-3-8B-Instruct-sft-webshop-iter{iter}
      prompt_template_file: prompts/webshop/webshop_template.j2
correct_student_trajectory:
  log_dir: data/webshop/corrections/iter{iter}/rollout
  output_log_dir: data/webshop/corrections/iter{iter}/correction 
  privileged_state_file: data/webshop/privileged_state.json
  prompt_file: prompts/webshop/correction_oracle_template.j2
  id_field_name: env_idx
  correct_score_threshold: 0
upload_models_to_hf:
  model_id_path: save/240902/webshop_sft/iter2/checkpoint-450
  new_model_name: Meta-Llama-3-8B-Instruct-sft-webshop-iter2
  organization_name: leap-llm