collect_logs:
  env_type: python
  env_image_name: intercode-python
  env_data_path: env_assets/intercode/data/python/mbpp/ic_mbpp.json
  env_verbose: false
  env_preprocess: null
  verbose: 0
  debug: false
  logdir: data/intercode_python/raw/raw_logs_w_reason
  exact_path: true
  eval_set: train
  start_env_idx: null
  max_env_idxs: null
  max_actions: 30
  agents:
    - type: openai
      model_id: gpt-4o
      prompt_template_file: prompts/intercode_python/intercode_python_react_template.j2
create_training_data:
  base_sft:
    prompt_template_file: prompts/intercode_python/intercode_python_template.j2
    logs_dir: data/intercode_python/raw/raw_logs_w_reason
    data_dir: data/intercode_python/sft/iter0
    train_split: 0.85
    input_fields:
      observation: observation
      reason: reason
      action: action
      task: task
    output_fields:
      reason: reason
      action: action
  sft:
    prompt_template_file: prompts/intercode_python/intercode_python_template.j2
    logs_dir: data/intercode_python/corrections/iter{prev_iter}/correction
    data_dir: data/intercode_python/sft/iter{iter}
    train_split: 0.85
    input_fields:
      observation: original_observation
      reason: original_reason
      action: original_action
      task: task
    output_fields:
      reason: corrected_reason
      action: corrected_action
upload_models_to_hf:
  model_id_path: save/2408/intercode_python/sft/iter0
  new_model_name: Meta-Llama-3-8B-Instruct-sft-intercode-python-iter0
  organization_name: leap-llm